### ISSUE TITLE
Cover the composite PK in EntityReader

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#145] opened 2016-08-21 08:02 UTC
When the job is restarted, it restarts from `Entity ID > Entity Checkpoint ID`. For those entity types having a single field as entity ID, everything works fine. However, for the composite PK, `Entity ID > Entity Checkpoint ID` is not explicit enough. We need to find a way to handle it.
### Example

Assume that there's an entity call `MyDate.class`, its composite ID is `(year, month, day)`. The dataset starts at `(2016, 04, 01)` and ends at `(2016, 08, 31)`. And now the job is interrupted at `(2016, 07, 15)`, so it should be restarted at `(2016, 07, 16)`.

However, if we use roughly an `criteria.addOrder( Order.asc( idName ) )`, this will be translated to the below SQL : 

``` sql
12:47:21,786 INFO  [stdout] (Batch Thread - 9)     where
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         (
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             this_.day>=? 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             and this_.month>=? 
12:47:21,786 INFO  [stdout] (Batch Thread - 9)             and this_.year>=?
12:47:21,786 INFO  [stdout] (Batch Thread - 9)         ) 
```

In this case, the job restarts from `(2016, 08, 16)` instead of `(2016, 07, 16)`, which is wrong.

**Comment by yrodiere** [comment] 2017-01-06 12:46
I think that's more a Hibernate ORM issue than a Hibernate Search issue. Maybe we could report this on the Hibernate ORM JIRA? I.e. request a way to customize the ordering of composite properties. It would be a new feature, but maybe it could make it into 6.0.

And by the way, as far as mass indexing is concerned, I'm not sure we care about the exact order. We just want it to be the same each time we run the mass indexing job.
In your example, restarting the job works fine, doesn't it? The ordering is a bit odd (day, then month, then year), but we end up indexing the whole dataset, and we only index twice the values that were in the partition that failed.

**Comment by mincong-h** [comment] 2017-01-15 09:43
> I think that's more a Hibernate ORM issue than a Hibernate Search issue. Maybe we could report this on the Hibernate ORM JIRA? I.e. request a way to customize the ordering of composite properties. It would be a new feature, but maybe it could make it into 6.0.

Could you help me to do this? By the way, I think it exists some kind of bridges which facilitate the fields connections, e.g. `DateBridge` and `TwoWayBridge`? I can't remember anymore. And maybe these bridges are for analyzers.

> And by the way, as far as mass indexing is concerned, I'm not sure we care about the exact order. We just want it to be the same each time we run the mass indexing job.

It depends on the indexing logic.

In the selection-by-ids approach, the current Hibernate Search approach, the order doesn't matter, because we use the ID for identify an entity directly.

In the selection-by-range approach, the current GSoC approach, the exact order does not matter but it must be unique. Partitions are defined with boundaries, composed by lower bound and upper bound. Only entities having IDs between these boundaries are supposed to be indexed. This mechanism relies on a unique order which won't be changed at different job executions (start / restart). You're right: we don't care about the exact order. For example, in entity `MyDate`, no matter the comparator is `dd-MM-yyyy`, `yyyy-MM-dd` or other valid comparators, as far as it covers the entire data range to index, it would be find.

But the comparator need to be the same for `WHERE` and `ORDER BY` in SQL, which is what I worried about. As you can see in the following code, for composite ID name `idName`, the restrictions _greater-than_ is defined via class `Restrictions` and then be translated into native SQL using a comparator. This mechanism is the same for ordering.

```java
criteria.add( Restrictions.gt( idName, unit.getLowerBound() ) )  // comparator 1
        .addOrder( Order.asc( idName ) )                         // same comparator ?
```

If `Restrictions` and `Order` use the same comparator, e.g. `dd-MM-yyyy`. This is fine. We'll have the below results in SQL:

```sql
SELECT year, month, day
FROM mydate
WHERE day > 15
  AND month >= 07
  AND year >= 2016
ORDER BY day, month, year
-- 2016 07 15 skipped
-- 2016 08 15
-- 2016 07 16
-- 2016 08 16
```

If `Restrictions` and `Order` use the different comparators, e.g. `dd-MM-yyyy` for `Restrictions` and `yyyy-MM-dd` for `Order`. This is not good. We'll have the below results in SQL:

```sql
SELECT year, month, day
FROM mydate
WHERE day > 15
  AND month >= 07
  AND year >= 2016
ORDER BY year, month, day
-- 2016 07 15 skipped
-- 2016 07 16
-- 2016 07 17
-- 2016 07 18
```

// I'm not finished and the above SQL examples are wrong. But I've to go now. I'll complete them later ...

**Comment by yrodiere** [comment] 2017-01-16 10:00
Thanks for the explanation. I'm not sure I understand how exactly the problem could arise, because from what I can see, in WHERE clauses the same operator is used on every column (unlike your example where ">" and ">=" are mixed). This means the ordering of columns does not change anything for where clauses, because the "AND" operator is symmetric. So these conditions are strictly equivalent (efficiency considerations aside):

```
day >= 15
AND month >= 07
AND year >= 2016
```

```
day >= 15
AND year >= 2016
AND month >= 07
```

```
year >= 2016
AND day >= 15
AND month >= 07
```

Etc.

Anyway, I agree it's worth some investigation, just to be sure: my algebra isn't what it used to be :)

From what I can see in the ORM code, `Restrictions.gt` uses a `SimpleExpression`. `SimpleExpression` uses `CriteriaQuery#findColumns` to retrieve the columns, which internally delegates to `CriteriaQueryTranslator#getColumns`.
`Order.property`, now, uses `CriteriaQuery.getColumnsUsingProjection`, which in our case will also delegate to `CriteriaQueryTranslator#getColumns`.
I looked at what's behind `CriteriaQueryTranslator#getColumns`, and I think it always returns the columns in the same order.

So both `Restrictions` and `Order` will render the columns in the same order, and thus we should be fine.

But if there isn't one already, maybe we could add a test case, just to be sure?

**Comment by yrodiere** [comment] 2017-02-21 09:37
Closing as duplicate of #155. There is an issue, but it's not the one we thought of initially (see https://github.com/mincong-h/gsoc-hsearch/issues/155#issuecomment-272860670)

**Closed by yrodiere** 2017-02-21 09:37 UTC
Labels: TODO
